/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MoguFoodDetector {
  constructor(modelPath: string)
  predict(tensor: MoguTensor): Array<PredictionResult>
  predictIsFood(tensor: MoguTensor): IsFoodResult
}

export declare class MoguImageProcessor {
  constructor(width: number, height: number)
  static withImagenetNormalization(width: number, height: number): MoguImageProcessor
  preprocess(buffer: Buffer): MoguTensor
}

export declare class MoguTensor {}

export interface IsFoodResult {
  isFood: boolean
  score: number
}

export interface PredictionResult {
  index: number
  probability: number
}
